version: "3.7"

services: 
  database_jobscrapper:
    image: postgres
    container_name: database_jobscrapper
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker123
      - POSTGRES_PASSWORD=jobscrapper321
      - POSTGRES_DB=jobscrapper_database
    volumes:
      - pgdata:/data/postgres
  jobscrapper_api: 
    build: .
    container_name: jobscrapper_api
    ports: 
      - 3333:3333
    volumes:
      - .:/app
    links:
      - database_jobscrapper
    env_file:
      - .env
    environment:
      - DATABASE_HOST=database_jobscrapper
      - DATABASE_USER=docker123
      - DATABASE_PASS=jobscrapper321
      - DATABASE_PORT=5432
      - DATABASE_NAME=jobscrapper_database

volumes:
  pgdata:
    driver: local
