version: "3.7"

services: 
  jobscrapper_api: 
    build: .
    container_name: jobscrapper_api
    ports: 
      - 3333:3333
    command: sh -c "npx ts-node ./node_modules/typeorm/cli.js migration:run -d src/database/data-source.ts && npm run dev"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
     - DATABASE_HOST=aws-0-us-west-1.pooler.supabase.com
     - DATABASE_USER=postgres.lyqvlzebnopaoqwdeohb
     - DATABASE_PASS=Qmqj2pYpCsBJCFooqbzG9sMf3kBNIrmL
     - DATABASE_NAME=postgres
     - DATABASE_PORT=5432
    dns:
      - 8.8.8.8
      - 8.8.4.4

volumes:
  pgdata:
    driver: local
