version: "3.7"

services: 
  jobscrapper_api: 
    build: .
    container_name: jobscrapper_api
    ports: 
      - 3333:3333
    command: sh -c "npx ts-node ./node_modules/typeorm/cli.js migration:run -d src/database/data-source.ts && npm run dev"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
     - DATABASE_HOST
     - DATABASE_USER
     - DATABASE_PASS
     - DATABASE_NAME
     - DATABASE_PORT
    dns:
      - 8.8.8.8
      - 8.8.4.4

volumes:
  pgdata:
    driver: local
